version: '3.9'

services:
  dev:
    image: yaga
    build:
      context: .
      target: build
    volumes:
      - '.:/app/yaga'
      - '../simple_matrix:/app/simple_matrix'
      - '../tilerender:/app/tilerender'
    logging:
      driver: none
