services:
  dev:
    image: yaga
    build:
      context: .
      target: build
    volumes: [ .:/app ]
    logging:
      driver: none

  examples:
    image: yaga:examples
    build: .
    logging:
      driver: none
