version: '3.8'

services:
  dev:
    image: yaga
    build:
      context: .
      target: build
    volumes:
      - '.:/app/yaga'
      - '../simple_matrix:/app/simple_matrix'
      - '../tilerender:/app/tilerender'
    logging:
      driver: none

  examples:
    image: yaga:examples
    build:
      context: .
      target: examples
    logging:
      driver: none
